Repository Taller-2/shared-server, pull requests merged in 2018-11, with the labels that each got.

#52 App servers graphics
  client/package.json
  client/src/App.js
  client/src/components/LoggedNavbar.js
  client/src/components/appServerGraphsForm.js
  client/src/components/rulesForm.js
  client/src/components/rulesListForm.js
  client/src/containers/appServerGraphsContainer.js
  package.json
  server/controllers/app_server_logged_data.js
  server/controllers/data_analysis.js
  server/controllers/http_service.js
  server/controllers/utils.js
  server/index.js
  server/routes/app_server_logged_data.js
  test/config_test.js
  test/data_analysis_definitions.js
  test/data_analysis_test.js
Labels: enhancement

#56 Fix: app sever table
  server/controllers/app_server.js
  server/migrations/20180930194344-create-app-server.js
  test/app_server_test.js
Labels: bug

#58 Fix: http service and app server logged sata controller
  package.json
  server/controllers/app_server_logged_data.js
  server/controllers/http_service.js
Labels: bug

#60 Refactor test
  server/controllers/app_server.js
  server/controllers/app_server_logged_data.js
  server/controllers/payment.js
  server/controllers/rules.js
  server/controllers/user.js
  server/migrations/20180902184339-create-user.js
  test/config_test.js
  test/shipment_cost_test.js
  test/user_test.js
Labels: enhancement

#67 Add more tests
  server/controllers/app_server_logged_data.js
  server/controllers/payment.js
  server/controllers/rules.js
  server/controllers/session.js
  server/controllers/shipment_cost.js
  server/controllers/user.js
  server/routes/rules.js
  test/add_rule_test.js
  test/payments_test.js
  test/shipment_cost_definitions.js
  test/shipment_cost_test.js
Labels: enhancement

#54 Shipments
  client/package.json
  client/public/css/bootstrap-theme.min.css
  client/public/css/bootstrap.min.css
  client/public/index.html
  client/src/App.js
  client/src/components/LoggedNavbar.js
  client/src/components/shipments/ShipmentForm.js
  client/src/components/shipments/ShipmentList.js
  client/src/containers/ShipmentsContainer.js
  client/src/i18n/messages-es.js
  package.json
  server/controllers/shipment.js
  server/enums/shipment_status.js
  server/index.js
  server/migrations/20181104221543-create-shipments.js
  server/models/shipment.js
  server/routes/shipments.js
  test/shipments_test.js
Labels: enhancement

#65 Refactor front end add rules
  client/src/components/rules.js
  client/src/components/rulesList.js
  client/src/components/rulesListForm.js
  client/src/containers/rulesContainer.js
  client/src/containers/rulesListContainer.js
  server/controllers/rules.js
  test/rules_definitions.js
  test/rules_test.js
Labels: bug, enhancement

#69 Fix shipments parameters
  server/controllers/shipment.js
  test/shipments_test.js
Labels: bug, enhancement

#71 Fix shipment cost
  client/src/components/rulesForm.js
  client/src/containers/rulesContainer.js
  server/controllers/rules.js
  server/routes/rules.js
  test/rules_test.js
Labels: bug

#77 Front end simulate shipment cost
  client/src/App.js
  client/src/components/LoggedNavbar.js
  client/src/components/rulesForm.js
  client/src/components/rules_data.js
  client/src/components/shipmentCostForm.js
  client/src/containers/rulesContainer.js
  client/src/containers/shipmentCostContainer.js
  package.json
  server/controllers/shipment_cost.js
  server/controllers/shipment_cost_data_types.js
  server/controllers/user.js
  server/routes/shipment_cost.js
  test/shipment_cost_definitions.js
  test/shipment_cost_test.js
  test/user_test.js
Labels: bug, enhancement

#79 Refactor: add Promise.all() to wait for the finalization of each promises
  test/shipment_cost_test.js
Labels: bug

#83 Fix app server graphics
  client/src/components/appServerGraphsForm.js
  client/src/containers/appServerGraphsContainer.js
Labels: bug, enhancement

#86 Readjust shipment cost
  client/src/components/rulesForm.js
  client/src/components/rules_data.js
  client/src/components/shipmentCostForm.js
  client/src/containers/shipmentCostContainer.js
  server/controllers/shipment_cost_data_types.js
  server/routes/shipment_cost.js
  test/shipment_cost_definitions.js
  test/shipment_cost_test.js
Labels: enhancement
